version: "3.8"

networks:
  walleto:
    external: true
    name: "walleto-network"
  default:
    external: true
    name: "default-network"

services:
  walleto:
    container_name: walleto
    image: nginx:1.19-alpine
    restart: always
    networks:
      - walleto
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./client/build:/usr/share/nginx/html
